# Generated by Django 4.1.7 on 2023-02-18 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="марка")),
                ("slug", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="имя тега")),
            ],
        ),
        migrations.CreateModel(
            name="Yarn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название товара",
                    ),
                ),
                ("length", models.IntegerField(verbose_name="длина мотка")),
                ("wieght", models.IntegerField(verbose_name="вес мотка")),
                (
                    "needles",
                    models.CharField(
                        max_length=255, verbose_name="рекомендуемые спицы"
                    ),
                ),
                ("description", models.TextField(verbose_name="большой описание")),
                ("price", models.FloatField(verbose_name="цена")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads",
                        verbose_name="изображение",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="yarn3.category",
                        verbose_name="категория",
                    ),
                ),
                (
                    "tag",
                    models.ManyToManyField(
                        blank=True, null=True, to="yarn3.tag", verbose_name="тег"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VariablesYarn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("color", models.CharField(max_length=255, verbose_name="номер цвета")),
                ("count", models.IntegerField(verbose_name="кол-во штук")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "productMain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="yarn3.yarn",
                    ),
                ),
            ],
        ),
    ]
