# Generated by Django 4.1.7 on 2023-02-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yarn3", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Производитель"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name_plural": "Состав"},
        ),
        migrations.AlterModelOptions(
            name="variablesyarn",
            options={"verbose_name_plural": "Номер цвета"},
        ),
        migrations.AlterModelOptions(
            name="yarn",
            options={"verbose_name_plural": "Пряжа"},
        ),
        migrations.AlterField(
            model_name="yarn",
            name="tag",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="tag",
                to="yarn3.tag",
                verbose_name="тег",
            ),
        ),
    ]
