# Generated by Django 4.1.7 on 2023-02-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yarn3", "0003_yarn_imagemain2_yarn_imagemain3_yarn_imagemain4_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="yarn",
            name="barcode",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="штрихкод"
            ),
        ),
        migrations.AddField(
            model_name="yarn",
            name="purchasePrice",
            field=models.FloatField(
                blank=True, null=True, verbose_name="закупочная цена"
            ),
        ),
    ]
