# Generated by Django 4.1.7 on 2023-02-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yarn3", "0005_yarn_discount_yarn_discountpercentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yarn",
            name="discount",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="скидка в рублях"
            ),
        ),
        migrations.AlterField(
            model_name="yarn",
            name="discountPercentage",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="скидка в процентах"
            ),
        ),
    ]
