# Generated by Django 4.1.7 on 2023-02-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yarn3", "0006_alter_yarn_discount_alter_yarn_discountpercentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variablesyarn",
            name="count",
            field=models.FloatField(verbose_name="кол-во штук"),
        ),
    ]
