# Generated by Django 4.1.7 on 2023-02-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yarn3", "0007_alter_variablesyarn_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variablesyarn",
            name="color",
            field=models.IntegerField(max_length=255, verbose_name="номер цвета"),
        ),
        migrations.AlterField(
            model_name="variablesyarn",
            name="count",
            field=models.IntegerField(verbose_name="кол-во штук"),
        ),
    ]
