# Generated by Django 4.1.7 on 2023-02-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yarn3", "0008_alter_variablesyarn_color_alter_variablesyarn_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variablesyarn",
            name="color",
            field=models.IntegerField(verbose_name="номер цвета"),
        ),
        migrations.AlterField(
            model_name="yarn",
            name="barcode",
            field=models.IntegerField(blank=True, null=True, verbose_name="штрихкод"),
        ),
    ]
