# Generated by Django 4.1.7 on 2023-02-25 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("needles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="length",
            options={"verbose_name_plural": "длинна"},
        ),
        migrations.AlterModelOptions(
            name="material",
            options={"verbose_name_plural": "Материал"},
        ),
        migrations.AlterModelOptions(
            name="type",
            options={"verbose_name_plural": "тип"},
        ),
        migrations.AlterModelOptions(
            name="variables",
            options={"verbose_name_plural": "Производитель"},
        ),
        migrations.AlterModelOptions(
            name="variablesitem",
            options={"verbose_name_plural": "вариации"},
        ),
    ]
