# Generated by Django 4.1.7 on 2023-02-25 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("needles", "0002_alter_length_options_alter_material_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="needles",
            options={"verbose_name_plural": "товар - спица"},
        ),
        migrations.AddField(
            model_name="needles",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="needles.variables",
                verbose_name="производитель",
            ),
        ),
        migrations.AddField(
            model_name="needles",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="описание товара"
            ),
        ),
        migrations.AddField(
            model_name="needles",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="needles.material",
                verbose_name="материал",
            ),
        ),
        migrations.AddField(
            model_name="needles",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Название товара"
            ),
        ),
        migrations.AddField(
            model_name="needles",
            name="typeNeedles",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="needles.type",
                verbose_name="тип(круговые, прямые)",
            ),
        ),
        migrations.AddField(
            model_name="needles",
            name="variablesItem",
            field=models.TextField(
                blank=True, null=True, verbose_name="вариации в формате JSON"
            ),
        ),
        migrations.AddField(
            model_name="variablesitem",
            name="name",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="вариации"
            ),
        ),
    ]
