# Generated by Django 4.1.7 on 2023-02-25 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Марка")),
            ],
        ),
        migrations.CreateModel(
            name="Spool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="название")),
                ("count", models.IntegerField(blank=True, verbose_name="количество")),
                (
                    "length",
                    models.CharField(blank=True, max_length=255, verbose_name="метраж"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="описание"
                    ),
                ),
                (
                    "image1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads",
                        verbose_name="изображение бобины_1",
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads",
                        verbose_name="изображение бобины_2",
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads",
                        verbose_name="изображение бобины_3",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="spool.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Бобины",
            },
        ),
    ]
