# Generated by Django 4.1.7 on 2023-02-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spool", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spool",
            name="image4",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="uploads",
                verbose_name="изображение бобины_4",
            ),
        ),
        migrations.AddField(
            model_name="spool",
            name="whole",
            field=models.BooleanField(default=False, verbose_name="подавать целиком"),
        ),
    ]
