# Generated by Django 4.1.7 on 2023-02-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spool", "0002_spool_image4_spool_whole"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spool",
            name="description",
            field=models.TextField(blank=True, verbose_name="описание"),
        ),
    ]
