# Generated by Django 4.1.7 on 2023-02-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spool", "0003_alter_spool_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="spool",
            name="price",
            field=models.FloatField(blank=True, null=True, verbose_name="цена"),
        ),
        migrations.AddField(
            model_name="spool",
            name="purchasePrice",
            field=models.FloatField(
                blank=True, null=True, verbose_name="закупочная цена"
            ),
        ),
    ]
