# Generated by Django 4.1.7 on 2023-02-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spool", "0004_spool_price_spool_purchaseprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="spool",
            name="barcode",
            field=models.IntegerField(blank=True, null=True, verbose_name="штрихкод"),
        ),
        migrations.AddField(
            model_name="spool",
            name="discount",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="скидка в рублях"
            ),
        ),
        migrations.AddField(
            model_name="spool",
            name="discountPercentage",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="скидка в процентах"
            ),
        ),
    ]
