---
version: '3.8'
services:
  db_mongo:
    image: mongo:4.4.4
    container_name: mongo-rerd-back
    restart: unless-stopped
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data-4.4:/data/db
