# Generated by Django 4.1.7 on 2023-02-27 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Length",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.FloatField(default=0, verbose_name="длинна")),
            ],
            options={
                "verbose_name_plural": "длинна",
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Материал")),
            ],
            options={
                "verbose_name_plural": "Материал",
            },
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="тип(круговые, прямые)"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "тип",
            },
        ),
        migrations.CreateModel(
            name="Variables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Производитель"),
                ),
            ],
            options={
                "verbose_name_plural": "Производитель",
            },
        ),
        migrations.CreateModel(
            name="VariablesItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True, max_length=100, null=True, verbose_name="вариации"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "вариации",
            },
        ),
        migrations.CreateModel(
            name="Needles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название товара",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="описание товара"
                    ),
                ),
                (
                    "variablesItem",
                    models.TextField(
                        blank=True, null=True, verbose_name="вариации в формате JSON"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="needles2.variables",
                        verbose_name="производитель",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="needles2.material",
                        verbose_name="материал",
                    ),
                ),
                (
                    "typeNeedles",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="needles2.type",
                        verbose_name="тип(круговые, прямые)",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "товар - спицы",
            },
        ),
    ]
