# Generated by Django 4.1.7 on 2023-02-26 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryKnitwear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="категория Вязанного изделия"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Knitwear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="название")),
                ("description", models.TextField(blank=True)),
                ("price", models.FloatField(verbose_name="цена")),
                (
                    "purchasePrice",
                    models.FloatField(
                        blank=True, null=True, verbose_name="закупочная цена"
                    ),
                ),
                (
                    "discount",
                    models.FloatField(
                        blank=True, default=0, null=True, verbose_name="скидка в рублях"
                    ),
                ),
                (
                    "discountPercentage",
                    models.FloatField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="скидка в процентах",
                    ),
                ),
                (
                    "barcode",
                    models.IntegerField(blank=True, null=True, verbose_name="штрихкод"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads",
                        verbose_name="изображение-1",
                    ),
                ),
                (
                    "imageMain2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads",
                        verbose_name="изображение-2",
                    ),
                ),
                (
                    "imageMain3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads",
                        verbose_name="изображение-3",
                    ),
                ),
                (
                    "imageMain4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads",
                        verbose_name="изображение-4",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="knitwearCategory",
                        to="knitwear.categoryknitwear",
                        verbose_name="категория",
                    ),
                ),
            ],
        ),
    ]
